# Generated by Django 5.0.6 on 2024-06-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudpdf',
            name='file_size',
        ),
    ]
